openapi: 3.0.0
servers:
  - url: 'https://bgtest.landregistry.gov.uk/api'
  - url: 'https://businessgateway.landregistry.gov.uk/api'
  - url: /v1
info:
  title: Organisation API
  description: Land Registry Organisation API
  version: 2.3.1
paths:
  /organisations:
    get:
      summary: Organisation
      operationId: getOrganisations
      description: >-
        This endpoint will return a JSON object containing a list of legal
        organisation names.
      parameters:
        - name: Content-Type
          in: header
          description: >-
            Pass 'application/json' to retrieve the organisation list
            successfully.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: >
            A list of all legal organisation names will be returned that can
            then be further queried.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organisation_List'
components:
  schemas:
    Organisation_List:
      description: A response that includes a list of legal organisation names.
      type: object
      additionalProperties: false
      properties:
        organisation_names:
          type: array
          items:
            type: string
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
